locales = []
[[paths]]
reference = "templates/mozilla-donate.pot"
l10n = "locales/{locale}/mozilla-donate.po"

[[paths]]
reference = "templates/mozilla-donate/fighting-back.pot"
l10n = "locales/{locale}/mozilla-donate/fighting-back.po"

